// solid-tryout/src/Clock.tsx
import { createSignal } from "solid-js";
import { customElement } from 'solid-element';


export default function SolidClock() {
  const [time, setTime] = createSignal(new Date());
  const formatter = new Intl.DateTimeFormat("en-US", {
    hour: "numeric",
    minute: "numeric",
    second: "numeric"
  });
  setInterval(() => {
    setTime(new Date())
  }, 1000)    
  return (
    <>
      <style>{`.clock{
        background-color: midnightblue;
        color: #ffffff;
        padding: 10px;
        width: 100px;
        border-radius: 4px;;
      }`}</style>
      <div class="clock">
            {formatter.format(time())}
    </div>
    </>
    
  )
  
}

customElement('solid-clock', {}, SolidClock);

// lit-tryout/src/components/clock.ts
import { LitElement, html, css } from "lit";
import { customElement, state } from "lit/decorators.js";

@customElement("lit-clock")
export class Clock extends LitElement {
  static styles = [
    css`
      :host {
        display: block;
      }
      .clock {
        background-color: midnightblue;
        color: #ffffff;
        padding: 10px;
        width: 100px;
        border-radius: 4px;
      }
    `,
  ];
  @state() private time = new Date();
  private formatter = new Intl.DateTimeFormat("en-US", {
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
  });

  connectedCallback(): void {
    super.connectedCallback();
    setInterval(() => {
      this.time = new Date();
    }, 1000);
  }

  render() {
    return html` <div class="clock">${this.formatter.format(this.time)}</div> `;
  }
}
